// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBbNkuF50rZmuqR5r-f9Uga0vyypsprqYU",
    authDomain: "srm-live-6d130.firebaseapp.com",
    projectId: "srm-live-6d130",
    storageBucket: "srm-live-6d130.appspot.com",
    messagingSenderId: "1039892070502",
    appId: "1:1039892070502:web:4675ecbab370430b892da7"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgViVqO4wfD3s9uTOI_SeYaCNyEZ-V3DA',
    appId: '1:1039892070502:android:f34cd5d7c24ff952892da7',
    messagingSenderId: '1039892070502',
    projectId: 'srm-live-6d130',
    storageBucket: 'srm-live-6d130.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMzlvwKKO2zn5xm4nGIDTSlNstyzLtLhc',
    appId: '1:1039892070502:ios:3ff79b374a49afd5892da7',
    messagingSenderId: '1039892070502',
    projectId: 'srm-live-6d130',
    storageBucket: 'srm-live-6d130.appspot.com',
    iosBundleId: 'com.example.srmLive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMzlvwKKO2zn5xm4nGIDTSlNstyzLtLhc',
    appId: '1:1039892070502:ios:aa24de0050c241f6892da7',
    messagingSenderId: '1039892070502',
    projectId: 'srm-live-6d130',
    storageBucket: 'srm-live-6d130.appspot.com',
    iosBundleId: 'com.example.srmLive.RunnerTests',
  );
}
